apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-prometheus-config
  namespace: monitoring
data:
  prometheus.yml: |
    scrape_configs:
      - job_name: "vault"
        static_configs:
          - targets: ["vault.vault.svc.cluster.local:8200"]
